name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "9c5874a9-1bee-4621-a0a4-0bc453fe592f"
migrations_dir = "./migrations"

# [ai]
# binding = "AI"

# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "blazenote"
# preview_bucket_name = "dev-blazenote"

[observability.logs]
enabled = true

# Custom domain configuration
[[routes]]
pattern = "blazenote-backend.pristine-quoter.sxplab.com"
custom_domain = true